spring:
  application:
    name: franchise-api
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/franchisedb}
      database: ${MONGO_DB:franchisedb}

server:
  port: ${PORT:8080}

logging:
  level:
    com.accenture.franchise: DEBUG
    org.springframework.data.mongodb: INFO
